
from pydantic import BaseModel, Field
import sys
from typing import Optional
import subprocess

from datetime import datetime
from helpers import LlmApi, MemoryPrompt, Log

class StepMetrics(BaseModel):
    """Metrics for a single agent step.
    Each step corresponds to one LLM generate -> sandbox execute cycle.
    All fields are required for evaluation, empty strings are acceptable
    for steps where a field doesn't apply (e.g., no sandbox execution).
    """

    step: int = Field(description="1-indexed iteration number")
    input_tokens: int = Field(default=0, description="Tokens sent to the LLM for this step")
    output_tokens: int = Field(default=0, description="Tokens generated by the LLM for this step")
    request_time_ms: float = Field(default=0, description="Wall-clock time for the LLM API call in milliseconds")
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat(), description="ISO 8601 timestamp of when this step was recorded")
    api_url: str = Field(default="", description="Base URL of the LLM API endpoint (e.g., 'https://openrouter.ai/api/v1')")
    model_name: str = Field(default="", description="Model identifier used for this step (e.g., 'qwen/qwen3-235b-a22b-2507')")
    llm_output: str = Field(default="", description="Raw text generated by the LLM before code extraction")
    sandbox_input: str = Field(default="", description="Python code sent to the sandbox for execution")
    sandbox_output: str = Field(default="", description="Sandbox execution result (stdout/stderr/error message)")
    retries: int = Field(default=0, description="Number of LLM API retries before getting a successful response (0 = first attempt succeeded)")

{
    "steps": [
        {
            "step": 1,
            "llm_output": "I'll read the file to understand the module.\n```python\nresult = read_file(filepath=\"/testbed/src/module.py\")\n```",
            "sandbox_input": "result = read_file(filepath=\"/testbed/src/module.py\")",
            "sandbox_output": "def solve(x):\n return x + 1\n...",
            "retries": 0,
            "input_tokens": 1234,
            "output_tokens": 567,
            "...": "..."
        }
    ]
}


class SolutionOutput(BaseModel):
    """Output from student solution, required format for evaluation.
    This is the JSON structure your agent must produce and write to solution.
    json.
    The moulinette validates this against task correctness and metrics limits.
    """
    task_id: str = Field(description="Task identifier (MBPP task_id a string, or SWE-bench instance_id)")
    benchmark: str = Field(description="Benchmark type: 'mbpp' or  swebench'")

    success: bool = Field(default=False, description="Whether the agent believes i solved the task")
    solution: str = Field(default="", description="For MBPP: the Python function code For SWE-bench: the git patch (diff)")
    iterations: int = Field(default=0, description="Number of agent loop iteration used")
    total_requests: int = Field(default=0, description="Total number of LLM AP requests made (including retries)")

    total_input_tokens: int = Field(default=0, description="Sum of input_token across all steps")
    total_output_tokens: int = Field(default=0, description="Sum of output_token across all steps")

    total_time_seconds: float = Field(default=0, description="Wall-clock time fro agent start to finish")
    steps: list[StepMetrics] = Field(default_factory=list, description="Per step metrics, one entry per agent iteration")
    system_prompt: str = Field(description="Full system prompt sen to the LLM (for provenance checking)")
    error: Optional[str] = Field(default=None, description="Error message i the agent failed (None if successful)")
    timestamp: str = Field(default_factory=lambda: datetime.now().isoformat(), description="ISO 8601 timestamp of when the solution was produced")


class Agent(SolutionOutput):
    model_config = {"arbitrary_types_allowed": True}

    output_path: str = Field(pattern=r".*\.json$")

    llmapi: LlmApi
    prompt: MemoryPrompt
    exec_result: str = ""
   
    def create_prompt(self) -> str:
        if self.exec_result:
            out = BasePrompts.get_aftercode_prompt(self.exec_result)
        else:
            out = BasePrompts.get_nocode_prompt()
        return out

    def next_step(self) -> bool:
   
        start = datetime.now()
        prompt = self.create_prompt()

        new = StepMetrics(step=len(self.steps) + 1)
        self.steps.append(new)
        self.prompt.add_message(prompt)
        resp = self.llmapi.response(self.prompt.messages)
        code = self.prompt.get_message_code(self.llmapi.get_current())

        self.exec_result = ""
        if code:
            command = ["uv", "run", "sandbox;", code]  # TODO use arguments in a json file
            result = subprocess.run(
                command,
                cwd=".",
                capture_output=True,
                text=True,
                check=True,
            )
            read = str(result.stdout)
            self.exec_result = read
            new.sandbox_input = code
            new.sandbox_output = read

        new.llm_output = resp["llm_output"]
        new.input_tokens = resp["input_tokens"]
        new.output_tokens = resp["output_tokens"]
        new.model_name = resp["model_name"]
        new.retries = resp["retries"]
        self.total_input_tokens += resp["input_tokens"]
        self.total_output_tokens += resp["output_tokens"]
        new.request_time_ms = datetime.now() - start

        print("[ STEP FINISHED ]------------------", file=sys.stderr) 
        for key, elem in new.__dict__.items():
            print(f"{key}|=|{elem}", file=sys.stderr)
        return False


""" SWE
Implement an agent CLI interface
# 1. Dump a task
cd moulinette
uv run moulinette_eval dump swebench --output ../cache/swebench_task.json
# 2. Run your agent
cd ../student
uv run python -m agent_swebench --task-file ../cache/swebench_task.json \
--output ../cache/swebench_solution.json \
--model-name "model/name" --provider-url "https://provider.api/v1"
# 3. Validate solution
cd ../moulinette
uv run moulinette_eval validate swebench ../cache/swebench_task.json \
../cache/swebench_solution.json
"""


class SWEBenchTaskInput(BaseModel):
    """Input for a SWE-bench task, provided by the moulinette.
    Your agent receives this and must produce a git patch that fixes
    the issue.
    """
    instance_id: str = Field(..., description="SWE-bench instance identifier (e.g., 'sympy__sympy-23534')")
    problem_statement: str = Field(..., description="The GitHub issue description, what needs to be fixed")
    docker_image: str = Field(..., description="Full Docker image name to pull (e.g., 'swebench/sweb.eval.x86_64. sympy_1776_sympy-23534:latest')")
    eval_script: str = Field(..., description="Bash script to run inside the container to evaluate the patch")
    hints_text: str = Field(default="", description="Optional hints about the issue (may be empty)")
    repo: str = Field(default="", description="Repository name (e.g., 'sympy/sympy')")


class SWEAgent(Agent):
    def __init__(self, taskinput: SWEBenchTaskInput) -> None:
        pass
    pass
