[project]
name = "42-Agent-Smith-MCP-server"
version = "0.00.0"
description = "Sub package for Agent-Smith project. This is the main MCP server, but others MCP servers can be used"
requires-python = ">= 3.10"
dependencies = [
		"flask",
		"httpx",
		"pydantic",
		"tree-sitter",
		"tree-sitter-language-pack",
		"GitPython",
		"jedi"
]
